compte/urls.py
from django.urls import path
from . import views

app_name = 'compte'

urlpatterns = [
    path('signup/', views.CustomUserCreateView.as_view(), name='signup'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('error_404/', views.error_404, name='error_404'),
]

moto/urls.py
from django.urls import path

from . import views
app_name = 'moto'
urlpatterns = [
    path('create_moto/', views.create_moto_with_images, name='create_moto'),
    path('detail_moto/<int:pk>/', views.detail_about_moto, name='detail_moto'),
    path('list_moto/', views.list_moto, name='list_moto'),
    path('list_moto_volee/', views.list_moto_volee, name='list_moto_volee'),
    path('declaration_vol/', views.declaration_vol, name='declaration_vol'),
    path('recherche_moto/', views.recherche_moto, name="recherche_moto")
]

nkamoto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from moto import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('moto/', include('moto.urls')),
    path('compte/', include('compte.urls')),
    path('commisariat/', include('commisariat.urls')),
    path('payment/', include('payment.urls')),
]
urlpatterns += staticfiles_urlpatterns()
# Servez les fichiers médias en mode développement
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

compte/models.py
import datetime
from django.db import models
from django.contrib.auth.models import AbstractUser


class NkamotoBase(models.Model):
    """
    Classe de base pour tous les modèles de l'application NKAMOTO,
    contenant des champs tels que la date de création et la date de modification.
    """
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class CustomUser(AbstractUser, NkamotoBase):
    """
    Modèle personnalisé pour les utilisateurs, héritant de NkamotoBase.
    """
    is_commissariat = models.BooleanField(default=False)
    email = models.EmailField(unique=True, null=True, blank=True)
    on_trial = models.BooleanField(default=True)
    
    
    # on trial is just for testing purposes of 13 days from the day of registration
    
    
    def still_on_trial(self):
        registration_date = self.created_at.date()
        today = datetime.date.today()
        difference = today - registration_date
        if difference.days > 13:
            self.on_trial = False
            self.save()
        return difference.days <= 13
    
    
    


class Profile(NkamotoBase):
    """
    Name : Profile
    Description : Modèle pour le profil des utilisateurs
    author : DonaldProgrammeur
    """
    numero_telephone = models.CharField(max_length=15)
    adresse_residence = models.CharField(max_length=255)
    numero_carte_identite = models.CharField(max_length=255)
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    photo_profil = models.ImageField(upload_to='profile/', null=True, blank=True)

compte/views.py
from django.shortcuts import redirect, render
from django.views import View
# Create your views here.
from .models import CustomUser
from django.contrib import messages 

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from moto.models import Moto, DeclarationVol
from commisariat.models import MotoVolee



class DashboardView(LoginRequiredMixin, View):
    """
    Name: DashboardView
    Description: Vue pour le tableau de bord
    Author: DonaldProgrammeur
    """
    
    template_name = 'dashboard/index.html'
    
    def get(self, request):
        vos_motos = Moto.objects.filter(proprietaire=request.user).count()
        vos_moto_volee = DeclarationVol.objects.filter(utilisateur=request.user).count()
        tous_les_motos_volees = MotoVolee.objects.all().count()
        context = {
            'vos_motos': vos_motos,
            'vos_moto_volee': vos_moto_volee,
            'tous_les_motos_volees': tous_les_motos_volees
        }
        print(context)
        return render(request, self.template_name, context)
    
    
    def post(self, request):
        return render(request, self.template_name)

class CustomLoginView(View):
    """
    Name: LoginView
    Description: Vue pour la connexion des utilisateurs
    Author: DonaldProgrammeur 
    """
    template_name = 'compte/login.html'
    
    def get(self, request):
        return render(request, self.template_name)
    
    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username = username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, f'Bienvenue, {user.username} Vous êtes connecté')
            return redirect('compte:dashboard')
        else:
            messages.error(request, 'Nom d\'utilisateur ou mot de passe incorrect')
        return render(request, self.template_name)
    
    
    
class CustomUserCreateView(View):
    """
    Name: CustomUserCreateView
    Description: Vue pour la création des utilisateurs
    Author: DonaldProgrammeur
    """
    
    template_name = 'compte/register.html'
    
    def get(self, request):
        return render(request, self.template_name)
    
    def post(self, request):
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        confirm_password = request.POST.get('password_confirm')
        
        if password != confirm_password:
            messages.error(request, 'Les mots de passe ne correspondent pas')
            return render(request, self.template_name)
        
        if CustomUser.objects.filter(username=username).exists():
            messages.error(request, 'Ce nom d\'utilisateur existe déjà. Veuillez en choisir un autre')
            return render(request, self.template_name)
        try:
            
            user = CustomUser.objects.create_user(username=username,
                                              email=email, password=password)
        except Exception as e:
            messages.error(request, f'Une erreur est survenue lors de la création de votre compte: {e}')
            return render(request, self.template_name)    
        
        if user is not None:
            messages.success(request, f'Votre compte a été créé avec succès')
            return redirect('compte:login')
        
        return render(request, self.template_name) 
    
    
class CustomUserUpdateView(View):
    """
    Name: CustomUserUpdateView
    Description: Vue pour la modification des utilisateurs
    Author: DonaldProgrammeur
    """
    
    template_name = 'compte/update_profile.html'
    
    def get(self, request):
        return render(request, self.template_name)
    
    def post(self, request):
        pass    
    
    
def logout_view(request):
    """
    Name: logout_view
    Description: Vue pour la déconnexion des utilisateurs
    Author: DonaldProgrammeur
    """
    logout(request)
    messages.success(request, 'Vous êtes déconnecté')
    return redirect('compte:login') 


  

def error_404(request, exception):
    data = {}
    return render(request,'compte/404.html', data)  


def error_500(request):
    data = {}
    return render(request,'compte/500.html', data)

templates/compte/dashboard.html
{% extends 'base.html' %}

{% block title %} Dashboard {% endblock %}
{% block style %} 
#nkamoto {
    background-color: #3D3D3D;
}
.card-box {
    margin-bottom: 20px;
}
.card-green {
    background-color: #4CAF50;
}
.card-blue {
    background-color: #2196F3;
}
.card-orange {
    background-color: #FF9800;
}
.card-red {
    background-color: #F44336;
}
.card-purple {
    background-color: #9C27B0;
}
</style>
{% endblock %}

{% block content %}
<div class="container mt-4">
<br>
<br>
<br>
    <div class="row">
        <div class="col-md-6 col-lg-2 col-xlg-2">
            <div class="card card-hover card-green">
                <div class="box text-center card-box">
                    <h1 class="font-light text-white">
                        <span class="">{{ vos_motos }}</span>
                    </h1>
                    <h6 class="text-white">Vos motos</h6>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-lg-2 col-xlg-2">
            <div class="card card-hover card-blue">
                <div class="box text-center card-box">
                    <h1 class="font-light text-white">  
                        <span class="">{{ vos_moto_volee }}</span>
                    </h1>
                    <h6 class="text-white">Vos moto volees </h6>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-lg-2 col-xlg-2">
            <div class="card card-hover card-orange">
                <div class="box text-center card-box">
                    <h1 class="font-light text-white">
                        <span class="">0</span>
                    </h1>
                    <h6 class="text-white"> Frais d'utilisation </h6>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-lg-2 col-xlg-2">
            <div class="card card-hover card-red">
                <div class="box text-center card-box">
                    <h1 class="font-light text-white">
                        <span class="">{{ tous_les_motos_volees }}</span>
                    </h1>
                    <h6 class="text-white">Moto signale </h6>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-lg-2 col-xlg-2">
            <div class="card card-hover card-purple">
                <div class="box text-center card-box">
                    <h1 class="font-light text-white">
                        <span class="">0</span>
                    </h1>
                    <h6 class="text-white">xxxxxxx</h6>
                </div>
            </div>
        </div>

        <div class="col-md-6 col-lg-2 col-xlg-2">
            <div class="card card-hover card-blue">
                <div class="box text-center card-box">
                    <h1 class="font-light text-white">
                        <span class="">0</span>
                    </h1>
                    <h6 class="text-white">xxxxxx</h6>
                </div>
            </div>
        </div>
        
    </div>
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
{% endblock %}

templates/compte/login.html
{% extends 'base.html' %}

{% block title %} connexion {% endblock %}
{% block style %} 
#nkamoto{
    background-color: #3D3D3D;
}
{% endblock %}



{% block content %}
<main class="d-flex w-100">
    <div class="container d-flex flex-column">
<div class="row">
    <div class="col-sm-10 col-md-8 col-lg-6 col-xl-5 mx-auto d-table h-100">
        <div class="d-table-cell align-middle">

            <div class="text-center mt-4">
                <h1 class="h2">Bienvenue</h1>
                <p class="lead">
                    Connectez-vous à votre compte NKAMOTO pour continuer
                </p>
            </div>

            <div class="card">
                <div class="card-body">
                    <div class="m-sm-3">
                        <form method='post'>
                            {% csrf_token %}
                            <div class="mb-3">
                                <label class="form-label">Nom d'utilisateur</label>
                                <input class="form-control form-control-lg" type="text" name="username" placeholder="Entrez votre nom d'utilisateur" />
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Mot de passe</label>
                                <input class="form-control form-control-lg" type="password" name="password" placeholder="Entrez votre mot de passe" />
                            </div>
                            <div>
                                <div class="form-check align-items-center">
                                    <input id="customControlInline" type="checkbox" class="form-check-input" value="remember-me" name="remember-me" checked>
                                    <label class="form-check-label text-small" for="customControlInline">Se souvenir de moi</label>
                                </div>
                            </div>
                            <div class="d-grid gap-2 mt-3">
                                <button type='submit' class="btn btn-lg btn-primary">Se connecter</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="text-center mb-3">
                Vous n'avez pas de compte ? <a href="{% url 'compte:signup' %}">Inscrivez-vous</a>
            </div>
        </div>
    </div>
</div>
</div>
</main>

{% endblock %}

templates/compte/register.html
{% extends 'base.html' %}
{% block title %} creation {% endblock %}
{% block style %} 
#nkamoto{
    background-color: #3D3D3D;
}
{% endblock %}
{% block content %}
<main class="d-flex w-100">
    <div class="container d-flex flex-column">
        <div class="row">
            <div class="col-sm-10 col-md-8 col-lg-6 col-xl-5 mx-auto d-table h-100">
                <div class="d-table-cell align-middle">

                    <div class="text-center mt-4">
                        <h1 class="h2">Inscription</h1>
                        <p class="lead">
                            Créez un compte pour accéder à NKAMOTO
                        </p>
                    </div>

                    <div class="card">
                        <div class="card-body">
                            <div class="m-sm-3">
                                <form method="post">
                                    {% csrf_token %}
                                    <div class="mb-3">
                                        <label class="form-label">Nom d'utilisateur </label>
                                        <input required class="form-control form-control-lg" type="text" name="username" placeholder="Entrez votre nom d'utilisateur " required />
                                    </div>
                                    
                                    <div class="mb-3">
                                        <label class="form-label">Adresse e-mail</label>
                                        <input class="form-control form-control-lg" type="email" name="email" placeholder="Entrez votre adresse e-mail" required />
                                    </div>
                                    
                                    <div class="mb-3">
                                        <label class="form-label">Mot de passe</label>
                                        <input required class="form-control form-control-lg" type="password" name="password" placeholder="Entrez votre mot de passe" required />
                                    </div>
                                    <div class="mb-3">
                                        <label class="form-label">Confimation Mot de passe</label>
                                        <input required class="form-control form-control-lg" type="password" name="password_confirm" placeholder="Reentrez votre mot de passe" required />
                                    </div>
                                    <div class="d-grid gap-2 mt-3">
                                        <button type="submit" class="btn btn-lg btn-primary">S'inscrire</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="text-center mb-3">
                        Vous avez déjà un compte ? <a href="{% url 'compte:login' %}">Connectez-vous</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock %}