moto/urls.py
from django.urls import path

from . import views
app_name = 'moto'
urlpatterns = [
    path('create_moto/', views.create_moto_with_images, name='create_moto'),
    path('detail_moto/<int:pk>/', views.detail_about_moto, name='detail_moto'),
    path('list_moto/', views.list_moto, name='list_moto'),
    path('list_moto_volee/', views.list_moto_volee, name='list_moto_volee'),
    path('declaration_vol/', views.declaration_vol, name='declaration_vol'),
    path('recherche_moto/', views.recherche_moto, name="recherche_moto")
]

nkamoto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from moto import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('moto/', include('moto.urls')),
    path('compte/', include('compte.urls')),
    path('commisariat/', include('commisariat.urls')),
    path('payment/', include('payment.urls')),
]
urlpatterns += staticfiles_urlpatterns()
# Servez les fichiers médias en mode développement
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

moto/models.py
from django.db import models
from django.urls import reverse

from compte.models import CustomUser, NkamotoBase

class DeclarationVol(NkamotoBase):
    """
    Modèle pour enregistrer les déclarations de vol, héritant de NkamotoBase.
    """
    utilisateur = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    moto = models.ForeignKey('moto.Moto', on_delete=models.CASCADE)
    date_vol = models.DateField()
    quartier = models.CharField(max_length=255)
    commentaire = models.TextField()

class Moto(NkamotoBase):
    """
    Modèle pour enregistrer les informations sur les motos, héritant de NkamotoBase.
    """
    numero_matricule = models.CharField(max_length=255)
    type_moto = models.CharField(max_length=255)
    proprietaire = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    description = models.TextField(null=True, blank=True, help_text='decrivez votre moto en quelques ligne.')
    
    def __str__(self):
        return self.numero_matricule
    
    
    def get_absolute_url(self):
        return reverse("moto:detail_moto", kwargs={"pk": self.pk})
    
    def get_list_image_of_moto(self):
        return self.images.all()
    

class ImageMoto(NkamotoBase):
    """
    Modèle pour stocker les images des motos, héritant de NkamotoBase.
    """
    moto = models.ForeignKey(Moto, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='motos/')
    
    def __str__(self):
        return f"Image de {self.moto}"
    
    

from django.db.models.signals import post_save
from django.dispatch import receiver
from commisariat import models

@receiver(post_save, sender=DeclarationVol)
def create_moto_volee(sender, instance, created, **kwargs):
    if created:
        moto_volee = models.MotoVolee(moto=instance.moto)
        moto_volee.commentaire = instance.commentaire  
        moto_volee.date_vol = instance.date_vol
        moto_volee.save()
    

moto/forms.py
# forms.py
from django import forms
from .models import Moto, ImageMoto

class MotoForm(forms.ModelForm):
    class Meta:
        model = Moto
        fields = ['numero_matricule', 'type_moto']
        

class ImageMotoForm(forms.ModelForm):
    class Meta:
        model = ImageMoto
        fields = ['image']

moto/views.py
from django.shortcuts import get_object_or_404, render
from django.views import View
from commisariat.models import MotoVolee
from moto.models import ImageMoto, Moto, DeclarationVol

from django.contrib import messages
class IndexView(View):
    """
    Name: IndexView
    Description: This class is used to render the index page.
    Author: DonaldProgrammeur 
    """
    def get(self, request):
        return render(request, 'index.html')
    
    
# views.py
from django.shortcuts import render, redirect
from .forms import MotoForm
from django.contrib.auth.decorators import login_required

@login_required
def create_moto_with_images(request):
    """ 
    Name: create_moto_with_images
    Descripton: This function is used to create a moto with images.
    """
    if request.method == 'POST':
        moto_form = MotoForm(request.POST)

        if moto_form.is_valid():
            moto = moto_form.save(commit=False)
            moto.proprietaire = request.user
            moto.save()
            for image in request.FILES.getlist('image'):
                ImageMoto.objects.create(moto=moto, image=image)

            return redirect('moto:detail_moto', pk=moto.pk)  # Redirigez vers une page de succès
    
    return render(request, 'moto/create_moto.html')
    
@login_required
def detail_about_moto(request, *args, **kwargs):
    """
    Name: detail_about_moto
    Description: This function is used to display the details of a moto.
    """
    pk = kwargs.get('pk')
    motos = Moto.objects.filter(pk=pk, proprietaire=request.user)
    moto = None
    if motos.exists():
        moto = motos.first()
    return render(request, 'moto/detail_moto.html', {'moto': moto})

@login_required
def list_moto(request):
    """
    Name: list_moto
    Description: This function is used to display the list of motos.
    """
    motos = Moto.objects.filter(proprietaire=request.user)
    return render(request, 'moto/list_moto.html', {'motos': motos})

@login_required
def list_moto_volee(request):
    """
    Name: list_moto_volee
    Description: This function is used to display the list steal moto.
    """
    motos = MotoVolee.objects.all()
    return render(request, 'moto/liste_moto_volee.html', {'motos': motos})


@login_required
def declaration_vol(request, *args, **kwargs):
    """
    Name: declaration_vol
    Description: This function is used to declare a stolen moto.
    """
    motos = Moto.objects.filter(proprietaire=request.user)
    if request.method == 'POST':
        moto_id = request.POST.get('moto')
        date_vol = request.POST.get('date_vol')
        quartier = request.POST.get('quartier')
        commentaire = request.POST.get('commentaire')
        moto = Moto.objects.get(pk=moto_id)
        if moto.proprietaire != request.user:
            messages.error(request, 'Vous ne pouvez pas déclarer le vol d\'une moto qui ne vous appartient pas')
            return render(request, 'moto/declaration_vol.html')
        else:
            DeclarationVol.objects.create(moto_id=moto_id, date_vol=date_vol, 
                                        quartier=quartier, 
                                        commentaire=commentaire, 
                                        utilisateur=request.user)
            messages.success(request, 'Votre déclaration de vol a été enregistrée avec succès')
        return redirect('moto:list_moto')    
    return render(request, 'moto/declaration_vol.html', {'motos': motos})



def recherche_moto(request, *args, **kwargs):
    """
    Name: recherche_moto
    Description: This function is used to search for a moto.
    """
    matricule = request.GET.get('matricule')
    if matricule:
        motos = Moto.objects.filter(numero_matricule__icontains=matricule)
        if not motos.exists():
            messages.info(request, 'Aucune moto trouvée ayant le matricule: {}'.format(matricule))
        else:
            moto = motos.first()
            messages.success(request, "Moto trouvée avec connectez vous pour avoir plus d'info dessus.")    
            return render(request, 'recherche_moto.html', {'moto': moto})
    return render(request, 'recherche_moto.html')

templates/moto/create_moto.html
{% extends 'dashboard/base.html' %}
{% block title %} creation {% endblock %}

{% block content %}


    <div class="container">

      <div class="text-center mt-4">
        <h1 class="h2">ENREGISTRER VOTRE MOTO</h1>
        <p class="lead">
            Enregistrer votre moto sur NKAMOTO
        </p>
    </div>

      <!-- template.html -->
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        
        <div class="form-group">
          <label for="id_numero_matricule">Numéro de Matricule :</label>
          <input type="text" name="numero_matricule" class="form-control" id="id_numero_matricule">
        </div>
        
        <div class="form-group">
          <label for="id_type_moto">Type de Moto :</label>
          <input type="text" name="type_moto" class="form-control" id="id_type_moto">
        </div>
      
        <div id="images">
          <div class="form-group">
            <label for="id_image">Image :</label>
            <input type="file" name="image" class="form-control" id="id_image">
          </div>
        </div>

      
        <button type="button" id="add_image" class="btn btn-primary">Ajouter une image</button>
        <button type="submit" class="btn btn-success">Enregistrer</button>
      </form>

    </div>
      


{% endblock %}

templates/moto/declaration_vol.html
{% extends 'dashboard/base.html' %}
{% block title %} creation {% endblock %}

{% block content %}


<div class='container'>
    
<div class="text-center mt-4">
    <h1 class="h2">DECLARATION VOLE</h1>
    <p class="lead">
        Declarer le vol de votre vehicule sur NKAMOTO
    </p>
</div>

                    



<form method="post">
    {% csrf_token %}
    
    <div class="form-group">
        <label for="moto">Choisissez la moto volee :</label>
        <select class="form-control" id="moto" name="moto">
            <option> Choisissez une moto </option>
            {% for moto in motos %}
                <option value="{{ moto.id }}">{{ moto.numero_matricule }}-{{moto.type_moto}}</option>
            {% endfor %}
            
        </select>
    </div>

    <div class="form-group">
        <label for="date_vol">Date du Vol :</label>
        <input type="date" class="form-control" id="date_vol" name="date_vol">
    </div>

    <div class="form-group">
        <label for="quartier">Quartier :</label>
        <input type="text" class="form-control" id="quartier" name="quartier">
    </div>

    <div class="form-group">
        <label for="commentaire">Commentaire :</label>
        <textarea class="form-control" id="commentaire" name="commentaire" rows="4"></textarea>
    </div>

    <button type="submit" class="btn btn-primary">Déclarer le Vol</button>
</form>


 



</div>


{% endblock %}

templates/moto/detail_moto.html
{% extends 'dashboard/base.html' %}
{% block title %} creation {% endblock %}


{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="d-table-cell align-middle">

                    <div class="text-center mt-4">
                        <h1 class="h2">DETAIL  
                            {% if moto.proprietaire == request.user %}
                            <a href="#" class="btn btn-primary">
                                <i class="fas fa-edit"></i>
                            </a>
                            <a href="#" class="btn btn-danger">
                                <i class="fas fa-trash-alt"></i>
                            </a>
                            {% endif %}
                        </h1>
                        <p class="lead">
                            Detail de votre moto sur NKAMOTO
                        </p>
                    </div>

                    <div class="row">

                        <div class="col-md-6">
                            <h2> Matricule: <strong class="text-success">  {{ moto.numero_matricule|upper }} </strong> </h2>
                        </div>

                        <div class="col-md-6">
                            <h2> Type:  {{ moto.type_moto|upper }} </h2>
                            
                        </div>

                    </div>

                    <div class="row">
                        <section id="portfolio" class="portfolio">
                            <div class="container">
                                <div class="section-title">
                                    <h2>Images</h2>
                                    <p></p>
                                </div>
                                <div class="row portfolio-container">
                                    {% for pic in moto.get_list_image_of_moto %}
                                        <div class="col-lg-4 col-md-3 portfolio-item filter-app">
                                            <img src="{{ pic.image.url }}" class="img-fluid" alt="">
                                            <div class="portfolio-info">
                                                <a href="{{ pic.image.url }}" data-gallery="portfolioGallery" class="portfolio-lightbox preview-link" title=""><i class="bx bx-plus"></i></a>
                                                <a href="#" class="details-link" title="More Details"><i class="bx bx-link"></i></a>
                                            </div>
                                        </div>
                                    {% empty %}
                                        <p class="text-center">Pas d'image</p>
                                    {% endfor %}
                                </div>
                            </div>
                        </section>
              
  
        
  
                    </div>
      



                </div>
            </div>
        </div>
    
    </div>


{% endblock %}

templates/moto/list_moto.html
{% extends 'dashboard/base.html' %}
{% block title %} liste {% endblock %}

{% block content %}

    <div class="container d-flex flex-column">
        <div class="row">
            <div class="col-sm-10 col-md-8 col-lg-6 col-xl-5 mx-auto d-table">
                <div class="d-table-cell align-middle">

                    <div class="text-center mt-4">
                        <h1 class="h2">LISTE MOTO</h1>
                        <p class="lead">
                            Liste de vos motos sur NKAMOTO
                        </p>
                    </div>

                    <input class="form-control" type="text" id="searchInput" placeholder="Recherche...">


                    <table class="table">
                        <thead>
                            <tr>
                                <th>Matricule</th>
                                <th>Type</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <!-- Iterate through motorcycles and create rows -->
                            {% for moto in motos %}
                                <tr>
                                    <td><a href="{{ moto.get_absolute_url }}">{{ moto.numero_matricule }}</a></td>
                                    <td>{{ moto.type_moto }}</td>
                                    <td>
                                        <a href="{{moto.get_absolute_url}}" class="btn btn-success">
                                            <i class="fas fa-eye"></i>
                                        </a>
                                        <a href="#" class="btn btn-primary">
                                            <i class="fas fa-edit"></i>
                                        </a>
                                        <a href="#" class="btn btn-danger">
                                            <i class="fas fa-trash-alt"></i>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>



                </div>
            </div>
        </div>
    
    </div>
  

{% endblock %}

templates/moto/liste_moto_volee.html
{% extends 'dashboard/base.html' %}
{% block title %} creation {% endblock %}
{% block content %}

    <div class="container d-flex flex-column">
        <div class="row">
            <div class="col-sm-10 col-md-8 col-lg-6 col-xl-5 mx-auto d-table ">
                <div class="d-table-cell align-middle">

                    <div class="text-center mt-4">
                        <h1 class="h2">LISTE DES MOTOS VOLEES</h1>
                        <p class="lead">
                            Liste deS motos volees et enregistees sur NKAMOTO
                        </p>
                    </div>

                    <input class="form-control" type="text" id="searchInput" placeholder="Recherche...">


                    <table class="table">
                        <thead>
                            <tr>
                                <th>Matricule</th>
                                <th>Type</th>
                                <th> Proprietaire</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <!-- Iterate through motorcycles and create rows -->
                            {% for moto in motos %}
                                <tr>
                                    <td>{{ moto.moto.numero_matricule }}</td>
                                    <td>{{ moto.moto.type_moto }}</td>
                                    <td>{{ moto.moto.proprietaire.username }}</td>
                                    <td>
                                        <a href="{{moto.get_absolute_url}}" class="btn btn-success">
                                            <i class="fas fa-eye"></i>
                                        </a>
                                        
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>



                </div>
            </div>
        </div>
    
    </div>
  

{% endblock %}