compte/urls.py
from django.urls import path
from . import views

app_name = 'compte'

urlpatterns = [
    path('signup/', views.CustomUserCreateView.as_view(), name='signup'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('error_404/', views.error_404, name='error_404'),
]

moto/urls.py
from django.urls import path

from . import views
app_name = 'moto'
urlpatterns = [
    path('create_moto/', views.create_moto_with_images, name='create_moto'),
    path('detail_moto/<int:pk>/', views.detail_about_moto, name='detail_moto'),
    path('list_moto/', views.list_moto, name='list_moto'),
    path('list_moto_volee/', views.list_moto_volee, name='list_moto_volee'),
    path('declaration_vol/', views.declaration_vol, name='declaration_vol'),
    path('recherche_moto/', views.recherche_moto, name="recherche_moto")
]

nkamoto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from moto import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('moto/', include('moto.urls')),
    path('compte/', include('compte.urls')),
    path('commisariat/', include('commisariat.urls')),
    path('payment/', include('payment.urls')),
]
urlpatterns += staticfiles_urlpatterns()
# Servez les fichiers médias en mode développement
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

moto/models.py
from django.db import models
from django.urls import reverse

from compte.models import CustomUser, NkamotoBase

class DeclarationVol(NkamotoBase):
    """
    Modèle pour enregistrer les déclarations de vol, héritant de NkamotoBase.
    """
    utilisateur = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    moto = models.ForeignKey('moto.Moto', on_delete=models.CASCADE)
    date_vol = models.DateField()
    quartier = models.CharField(max_length=255)
    commentaire = models.TextField()

class Moto(NkamotoBase):
    """
    Modèle pour enregistrer les informations sur les motos, héritant de NkamotoBase.
    """
    numero_matricule = models.CharField(max_length=255)
    type_moto = models.CharField(max_length=255)
    proprietaire = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    description = models.TextField(null=True, blank=True, help_text='decrivez votre moto en quelques ligne.')
    
    def __str__(self):
        return self.numero_matricule
    
    
    def get_absolute_url(self):
        return reverse("moto:detail_moto", kwargs={"pk": self.pk})
    
    def get_list_image_of_moto(self):
        return self.images.all()
    

class ImageMoto(NkamotoBase):
    """
    Modèle pour stocker les images des motos, héritant de NkamotoBase.
    """
    moto = models.ForeignKey(Moto, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='motos/')
    
    def __str__(self):
        return f"Image de {self.moto}"
    
    

from django.db.models.signals import post_save
from django.dispatch import receiver
from commisariat import models

@receiver(post_save, sender=DeclarationVol)
def create_moto_volee(sender, instance, created, **kwargs):
    if created:
        moto_volee = models.MotoVolee(moto=instance.moto)
        moto_volee.commentaire = instance.commentaire  
        moto_volee.date_vol = instance.date_vol
        moto_volee.save()
    

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>NKAMOTO | {% block title %} {% endblock %}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <!-- Add FontAwesome CSS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet">

  <style>
    #nkamoto{
      background-color: #3D3D3D;
  }
    {% block style %}
    {% endblock %}
  </style>
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top ">
    <div class="container-fluid">

      <div class="row justify-content-center">
        <div id="nkamoto" class="col-xl-9 d-flex align-items-center justify-content-lg-between">
          <h1 class="logo me-auto me-lg-0"><a href="/">NKAMOTO</a></h1>
          <!-- Uncomment below if you prefer to use an image logo -->
          <!-- <a href="index.html" class="logo me-auto me-lg-0"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

          <nav id="navbar" class="navbar order-last order-lg-0">
            <ul>
              
              <li><a class="nav-link scrollto active" href="/">Acceuil</a></li>
              <li><a class="nav-link scrollto" href="#about">A propos</a></li>
              <li><a class="nav-link scrollto" href="#services">Services</a></li>
              <li><a class="nav-link scrollto " href="#portfolio">Portfolio</a></li>
              <li><a class="nav-link scrollto" href="#pricing">Tarif</a></li>
              
          
              <li><a class='nav-link' href="{% url 'moto:recherche_moto' %}"> Recherchez une moto </a>
             
              <li><a class="nav-link scrollto" href="#contact">Contact</a></li>
            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>
          </nav><!-- .navbar -->
          <a href="{% url 'compte:dashboard' %}" class="get-started-btn">Tableau de bord</a>
      
        </div>
      </div>

    </div>
  </header><!-- End Header -->

<br><br><br>
    <div class="row my-10">
      {% if messages %}
      {% for message in messages %}
          <div class="container-fluid p-0">
              <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="True">&times;</span>
                  </button>
                  {{ message|safe }}
              </div>
          </div>
      {% endfor %}
    {% endif %}
  </div>


  {% block content %}
  

  {% endblock %}


   <!-- ======= Footer ======= -->
   <footer id="footer">
    <div class="container">
      <h3>NKAMOTO</h3>
      <p>Chez NKAMOTO, nous sommes passionnés par les motos, tout comme vous. Notre objectif est de fournir une solution simple et efficace pour aider les propriétaires de motos à retrouver leurs précieux engins en cas de vol</p>
      <div class="social-links">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
      <div class="copyright">
        &copy; Copyright <strong><span>NKAMOTO</span></strong>. Tous droits reservés
      </div>
      <div class="credits">
        
        developpeé par <a href="https://donaldprogrammeur.com/">DonaldProgrammeur</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

  <script>
    $(document).ready(function() {
      $("#add_image").click(function() {
        var newImageField = '<div class="form-group">' +
          '<label for="id_image">Image :</label>' +
          '<input type="file" name="image" class="form-control" id="id_image">' +
          '</div>';
        $("#images").append(newImageField);
      });
    });
  </script>

<script>
    $(document).ready(function() {
        $("#searchInput").on("keyup", function() {
            var value = $(this).val().toLowerCase();
            $("table tbody tr").filter(function() {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1);
            });
        });
    });
</script>


{% block js %} {% endblock %}
</body>

</html>

templates/recherche_moto.html
{% extends 'base.html' %}

{% block title %} 
    recheche Moto 
{% endblock %}

{% block style %} 
    #nkamoto {
        background-color: #3D3D3D;
    }
{% endblock %}

{% block content %}
<main class="d-flex">
    <div class="container">

        <br><br><br>
        <form method="get">
            <div class="input-group mb-3">
                <input name="matricule" class="form-control" placeholder="Entre le matricule de la moto" required>
                <button type="submit" class="btn btn-primary">Recherche</button>
            </div>
        </form>
        <br><br><br>
        
        {% if moto %}

        <div class="row">
            <div class="col-sm-10 col-md-8 col-lg-6 col-xl-5 mx-auto d-table h-100">
                <div class="d-table-cell align-middle">
                    <div class="text-center mt-4">
                        <h1 class="h2">DETAIL MOTO</h1>
                        <p class="lead">Détail moto sur NKAMOTO</p>
                    </div>

                    <div class="row text-center">
                        <div class="col-md-6">
                            <h4><u>Matricule:</u></h4>
                            <p><strong class="text-success">{{ moto.numero_matricule|upper }}</strong></p>
                        </div>

                        <div class="col-md-6">
                            <h4><u>Type:</u></h4>
                            <p>{{ moto.type_moto|upper }}</p>
                            {% if moto.proprietaire == request.user %}
                                <a href="#" class="btn btn-primary">
                                    <i class="fas fa-edit"></i>
                                </a>
                                <a href="#" class="btn btn-danger">
                                    <i class="fas fa-trash-alt"></i> 
                                </a>
                            {% endif %}
                        </div>
                    </div>
                    {% if request.user.is_authenticated %}
                    <p class="text-center"><b>Description</b>: {{ moto.description }}</p>
                    {% else %}
                    <p class="text-center"><b>Description</b>: {{ moto.description|truncatewords:20 }}.... <a href="{% url 'compte:login' %}"> conectez vous pour avoir tous les informations </a></p>

                    {% endif %}
                    {% if request.user.is_authenticated %}

                    <section id="portfolio" class="portfolio">
                        <div class="container">
                            <div class="section-title">
                                <h2>Images</h2>
                                <p></p>
                            </div>
                            <div class="row portfolio-container">
                                {% for pic in moto.get_list_image_of_moto %}
                                    <div class="col-lg-4 col-md-3 portfolio-item filter-app">
                                        <img src="{{ pic.image.url }}" class="img-fluid" alt="">
                                        <div class="portfolio-info">
                                            <h4>{{ moto.numero_matricule }}</h4>
                                            <p>{{ moto.type_moto }}</p>
                                            <a href="{{ pic.image.url }}" data-gallery="portfolioGallery" class="portfolio-lightbox preview-link" title=""><i class="bx bx-plus"></i></a>
                                            <a href="#" class="details-link" title="More Details"><i class="bx bx-link"></i></a>
                                        </div>
                                    </div>
                                {% empty %}
                                    <p class="text-center">Pas d'image</p>
                                {% endfor %}
                            </div>
                        </div>
                    </section>

                        <div class="row">
                            <div class="col-md-6">
                                <h6><u>Informations du Commissariat</u></h6>
                                {% comment %} <p><strong>Nom:</strong> {{ moto.commisariat.nom_commissariat }}</p>
                                <p><strong>Adresse:</strong> {{ moto.commisariat.adresse_commissariat }}</p>
                                <p><strong>Téléphone:</strong> {{ moto.commisariat.telephone_commissariat }}</p>
                                <p><strong>Email:</strong> {{ moto.commisariat.email_commissariat }}</p>
                                <p><strong>Ville:</strong> {{ moto.commisariat.ville_commissariat }}</p>
                                <p><strong>Responsable:</strong> {{ moto.commisariat.responsable_commissariat.username }}</p> {% endcomment %}
                            </div>
                            <div class="col-md-6">
                                <h6><u>Informations du Propriétaire</u></h6>
                                <p><strong>Nom:</strong> {{ moto.proprietaire.username }}</p>
                                <p><strong>Téléphone:</strong> {{ moto.proprietaire.profile.telephone }}</p>
                                <p><strong>Email:</strong> {{ moto.proprietaire.profile.email }}</p>
                                <p><strong>Adresse:</strong> {{ moto.proprietaire.profile.adresse }}</p>
                                <p><strong>Ville:</strong> {{ moto.proprietaire.profile.ville }}</p>
                                <p><strong>Quartier:</strong> {{ moto.proprietaire.profile.quartier }}</p>
                            </div>
                        </div>

                   {% endif %}     
                        
            </div>
        </div>

        {% endif %}
    </div>

    
</main>
{% endblock %}