compte/urls.py
from django.urls import path
from . import views

app_name = 'compte'

urlpatterns = [
    path('signup/', views.CustomUserCreateView.as_view(), name='signup'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('error_404/', views.error_404, name='error_404'),
]

moto/urls.py
from django.urls import path

from . import views
app_name = 'moto'
urlpatterns = [
    path('create_moto/', views.create_moto_with_images, name='create_moto'),
    path('detail_moto/<int:pk>/', views.detail_about_moto, name='detail_moto'),
    path('list_moto/', views.list_moto, name='list_moto'),
    path('list_moto_volee/', views.list_moto_volee, name='list_moto_volee'),
    path('declaration_vol/', views.declaration_vol, name='declaration_vol'),
    path('recherche_moto/', views.recherche_moto, name="recherche_moto")
]

nkamoto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from moto import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('moto/', include('moto.urls')),
    path('compte/', include('compte.urls')),
    path('commisariat/', include('commisariat.urls')),
    path('payment/', include('payment.urls')),
]
urlpatterns += staticfiles_urlpatterns()
# Servez les fichiers médias en mode développement
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from .views import PaymentView


app_name = 'payment'
urlpatterns = [
    path('', PaymentView.as_view(), name='payment'),
]

moto/models.py
from django.db import models
from django.urls import reverse

from compte.models import CustomUser, NkamotoBase

class DeclarationVol(NkamotoBase):
    """
    Modèle pour enregistrer les déclarations de vol, héritant de NkamotoBase.
    """
    utilisateur = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    moto = models.ForeignKey('moto.Moto', on_delete=models.CASCADE)
    date_vol = models.DateField()
    quartier = models.CharField(max_length=255)
    commentaire = models.TextField()

class Moto(NkamotoBase):
    """
    Modèle pour enregistrer les informations sur les motos, héritant de NkamotoBase.
    """
    numero_matricule = models.CharField(max_length=255)
    type_moto = models.CharField(max_length=255)
    proprietaire = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    description = models.TextField(null=True, blank=True, help_text='decrivez votre moto en quelques ligne.')
    
    def __str__(self):
        return self.numero_matricule
    
    
    def get_absolute_url(self):
        return reverse("moto:detail_moto", kwargs={"pk": self.pk})
    
    def get_list_image_of_moto(self):
        return self.images.all()
    

class ImageMoto(NkamotoBase):
    """
    Modèle pour stocker les images des motos, héritant de NkamotoBase.
    """
    moto = models.ForeignKey(Moto, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='motos/')
    
    def __str__(self):
        return f"Image de {self.moto}"
    
    

from django.db.models.signals import post_save
from django.dispatch import receiver
from commisariat import models

@receiver(post_save, sender=DeclarationVol)
def create_moto_volee(sender, instance, created, **kwargs):
    if created:
        moto_volee = models.MotoVolee(moto=instance.moto)
        moto_volee.commentaire = instance.commentaire  
        moto_volee.date_vol = instance.date_vol
        moto_volee.save()
    

templates/dashboard/include/footer.html
{% load static %}


<!-- Footer -->
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; NKAMOTO 2023</span>
        </div>
    </div>
</footer>
<!-- End of Footer -->

</div>
<!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
<i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
aria-hidden="true">
<div class="modal-dialog" role="document">
<div class="modal-content">
    <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Prêt à partir?</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
    </div>
    <div class="modal-body">Sélectionnez « Déconnexion » ci-dessous si vous êtes prêt à mettre fin à votre session en cours.</div>
    <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">Annuler</button>
        <a class="btn btn-primary" href="{% url 'compte:logout' %}">Déconnexion</a>
    </div>
</div>
</div>
</div>



<!-- Bootstrap core JavaScript-->
<script src="{% static 'dashboard/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'dashboard/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'dashboard/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'dashboard/js/sb-admin-2.min.js' %}"></script>

<!-- Page level plugins -->
<script src="{% static 'dashboard/vendor/chart.js/Chart.min.js' %}"></script>

<!-- Page level custom scripts -->
<script src="{% static 'dashboard/js/demo/chart-area-demo.js' %}"></script>
<script src="{% static 'dashboard/js/demo/chart-pie-demo.js' %}"></script>


<script>
    $(document).ready(function() {
        $("#add_image").click(function() {
        var newImageField = '<div class="form-group">' +
            '<label for="id_image">Image :</label>' +
            '<input type="file" name="image" class="form-control" id="id_image">' +
            '</div>';
        $("#images").append(newImageField);
        });
    });

      
</script>

<script>
    $(document).ready(function() {
        $("#searchInput").on("keyup", function() {
            var value = $(this).val().toLowerCase();
            $("table tbody tr").filter(function() {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1);
            });
        });
    });
</script>

templates/dashboard/include/header.html
<!-- Topbar -->
{% load static %}
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Search -->
    <form
        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
        <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                    <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
        </div>
    </form>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small"
                            placeholder="Recherche...." aria-label="Search"
                            aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        <!-- Nav Item - Alerts -->
        <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i>
                <!-- Counter - Alerts -->
                <span class="badge badge-danger badge-counter">0</span>
            </a>
            <!-- Dropdown - Alerts -->
            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="alertsDropdown">
                <h6 class="dropdown-header">
                    Centre d'alerte
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                        <div class="icon-circle bg-primary">
                            <i class="fas fa-file-alt text-white"></i>
                        </div>
                    </div>
                    <div>
                        <div class="small text-gray-500">Administration</div>
                        <span class="font-weight-bold">Passez a pro pour avoir plus de fonctionalites.</span>
                    </div>
                </a>
               
                
                <a class="dropdown-item text-center small text-gray-500" href="#">Voir tous les Alerts</a>
            </div>
        </li>

        <!-- Nav Item - Messages -->
        <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-envelope fa-fw"></i>
                <!-- Counter - Messages -->
                <span class="badge badge-danger badge-counter">0</span>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="messagesDropdown">
                <h6 class="dropdown-header">
                    Centre des message
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="{% static 'dashboard/img/undraw_profile_1.svg' %}"
                            alt="...">
                        <div class="status-indicator bg-success"></div>
                    </div>
                    <div class="font-weight-bold">
                        <div class="text">Salue nous experons que le systeme fonctione bien</div>
                        <div class="small text-gray-500">Administration · 58m</div>
                    </div>
                </a>
                
                
                <a class="dropdown-item text-center small text-gray-500" href="#">Lire tous les messages</a>
            </div>
        </li>

        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ request.user.get_fullname }}</span>
                <img class="img-profile rounded-circle"
                    src="{% static 'dashboard/img/undraw_profile.svg' %}">
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Profile
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                    parametrage
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                    Activites
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Deconnexion
                </a>
            </div>
        </li>

    </ul>

</nav>
<!-- End of Topbar -->

templates/dashboard/include/meta.html
{% load static %}

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">

<title>MKAMOTO | {% block title %}  {% endblock %}</title>

<!-- Custom fonts for this template-->
<link href="{% static 'dashboard/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
<link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">

<!-- Custom styles for this template-->
<link href="{% static 'dashboard/css/sb-admin-2.min.css' %}" rel="stylesheet">

templates/dashboard/include/sidebar.html
<!-- Sidebar -->
{% load static %}
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'compte:dashboard' %}">
        <div class="sidebar-brand-icon rotate-n-15">
            <img with="50px" height="50px" src="{% static 'dashboard/img/logo.png' %}">
        </div>
        <div class="sidebar-brand-text mx-3"> NKAMOTO <sup></sup></div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'compte:dashboard' %}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>NKAMOTO</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Interface
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
            aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-cog"></i>
            <span>Moto</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">moto</h6>
                <a class="collapse-item" href="{% url 'moto:list_moto' %}">liste moto</a>
                <a class="collapse-item" href="{% url 'moto:create_moto' %}">enregistrer une moto</a>
            </div>
        </div>
    </li>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseT"
            aria-expanded="true" aria-controls="collapseT">
            <i class="fas fa-dollar-sign"></i>
            <span>Payments</span>
        </a>
        <div id="collapseT" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Payment</h6>
                <a class="collapse-item" href="#">liste payment</a>
                <a class="collapse-item" href="{% url 'payment:payment' %}">Faire un paiement</a>
            </div>
        </div>
    </li>

    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
            aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-wrench"></i>
            <span>Volee</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
            data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Vole</h6>
                <a class="collapse-item" href="{% url 'moto:list_moto_volee' %}">liste des moto volees </a>
                <a class="collapse-item" href="{% url 'moto:declaration_vol'  %}">declarer un vole</a>
                {% comment %} <a class="collapse-item" href="utilities-animation.html">Animations</a>
                <a class="collapse-item" href="utilities-other.html">Other</a> {% endcomment %}
            </div>
        </div>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Compte
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
            aria-expanded="true" aria-controls="collapsePages">
            <i class="fas fa-fw fa-folder"></i>
            <span>compte</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">{{request.user.get_fullname|upper}}</h6>
                <a class="collapse-item" href="{% url 'compte:logout' %}">Deconnexion</a>
                <a class="collapse-item" href="#">Changer de mot de passe</a>
                {% comment %} <div class="collapse-divider"></div>
                <h6 class="collapse-header">Other Pages:</h6>
                <a class="collapse-item" href="404.html">404 Page</a>
                <a class="collapse-item" href="blank.html">Blank Page</a> {% endcomment %}
            </div>
        </div>
    </li>

    

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

    <!-- Sidebar Message -->
    <div class="sidebar-card d-none d-lg-flex">
        <img class="sidebar-card-illustration mb-2" src="{% static 'dashboard/img/undraw_rocket.svg' %}" alt="...">
        <p class="text-center mb-2"><strong>NKAMOTO Pro</strong> Ajouter plus de fonctionalites !</p>
        <a class="btn btn-success btn-sm" href="#">Passez à Pro!</a>
    </div>

</ul>
<!-- End of Sidebar -->